# Generated by Django 4.2.4 on 2023-09-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songsword',
            name='url_youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
